name: Build and Deploy Storybook

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy-storybook:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          folder: docs
          branch: gh-pages
